<a href="https://colab.research.google.com/github/MohammadHammoudeh14/London_bikes/blob/main/london_bikes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [24]:
# loading CSV data to a Pandas DataFrame
path = '/content/drive/MyDrive/Data /london_bikes.csv'
bikes = pd.read_csv(path)
bikes.head()

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [25]:
bikes.shape

(17414, 10)

In [26]:
# count the unique values in the weather_code column
bikes.weather_code.value_counts()

weather_code
1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: count, dtype: int64

In [27]:
# Count the unique values in season column
bikes.season.value_counts()

season
0.0    4394
1.0    4387
3.0    4330
2.0    4303
Name: count, dtype: int64

In [28]:
# changing ciloumns names
new_names = { 'timestamp':'time',
             'cnt':'count',
              't1':'temp_real_c',
              't2':'temp_feels_like_C',
              'hum':'humidity_percent',
              'wind_speed':'wind_speed_kph',
              'weather_code':'weather',
              'is_holiday':'is_holiday',
              'is_weekend':'is_weekend',
              'season':'season'
              }

# Renaming the columns to the specified column names
bikes.rename(new_names, axis=1, inplace=True)

In [30]:
# changing the humidity values to percentage (i.e. a value between 0 and 1)
bikes.humidity_percent = bikes.humidity_percent / 100

In [35]:
# Crear a season dictionary to change numeric values to STR
season_dict = { '0.0':'spring',
               '1.0':'summer',
                '2.0':'autumn',
                '3.0':'winter'}

# Crear a weather dictionary to change numeric values to STR
weather_dict = {
    '1.0':'Clear',
    '2.0':'Scattered clouds',
    '3.0':'Broken clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with thunderstorm',
    '26.0':'Snowfall'
}

# cahnge season datatype to string
bikes.season = bikes.season.astype("str")
# mapping the values 0-3 to the actual written seasons
bikes.season = bikes.season.map(season_dict)

# cahnge weather datatype to string
bikes.weather = bikes.weather.astype("str")
# mapping the values 0-3 to the actual written seasons
bikes.weather = bikes.weather.map(weather_dict)

In [36]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time               17414 non-null  object
 1   count              17414 non-null  int64
 2   temp_real_c        17414 non-null  float64
 3   temp_feels_like_C  17414 non-null  float64
 4   humidity_percent   17414 non-null  float64
 5   wind_speed_kph     17414 non-null  float64
 6   weather            17414 non-null  object
 7   is_holiday         17414 non-null  float64
 8   is_weekend         17414 non-null  float64
 9   season             17414 non-null  object
dtypes: float64(6), int64(1), object(3)
memory usage: 1.3+ MB

In [37]:
# Export data to EXCEL files then use it in tableau to make dashboard
bikes.to_excel('London_bikes_final.xlsx', index=False)
from google.colab import files
files.download('London_bikes_final.xlsx')